stages:
  prepare:
    cmd: python3 src/prepare.py
    deps:
      - src/prepare.py
    params:
      - prepare.categories
    outs:
      - data/raw
  featurize:
    cmd: python3 src/featurize.py data/raw data/features
    deps:
      - data/raw
      - src/featurize.py
    outs:
      - data/features
  train:
    cmd: python3 src/train.py data/features models/model.pkl
    deps:
      - data/features
      - src/train.py
    params:
      - train.alpha
    outs:
      - models/model.pkl
  evaluate:
    cmd: python3 src/evaluate.py models/model.pkl data/features logs/metrics.json logs/plots.json
    deps:
      - data/features
      - models/model.pkl
      - src/evaluate.py
    metrics:
      - logs/metrics.json:
          cache: false
    plots:
      - logs/plots.json:
          cache: false
